workflows:
  #--------------STAGING--------------
  staging-android-workflow:
    name: Android Build
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      vars:
        PROJECT: Digirh
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'staging'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --release --obfuscate --split-debug-info=./
      - name: Move the build into root directory
        script: |
          mv "build/app/outputs/apk/release/app-release.apk" "./$PROJECT-release.apk"
    artifacts:
      - ./*.apk
      - ./app.*.symbols
    publishing:
      email:
        recipients:
          - agtari957@gmail.com

  staging-ios-workflow:
    name: iOS Build
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.stb.digirh
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'staging'
          include: true
          source: true
    scripts:
      - name: Clean cache
        script: |
          rm pubspec.lock
          flutter packages pub get
      - name: Use the profile in Xcode
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Update Firebase/CoreOnly dependency
        script: |
          find . -name "Podfile" -execdir pod update Firebase/CoreOnly \;
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA with Flutter
        script: | 
          flutter build ipa --release 
      - name: Sign IPA with Xcode
        script: |
          xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner"
    artifacts:
      - ./build/ios/ipa/*.ipa
