name: digirh
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  auto_route: ^8.0.3
  table_calendar: ^3.0.9
  intl: ^0.19.0
  get_it:
  shared_preferences:
  dio:
  equatable:
  flutter_dotenv: ^5.1.0
  flutter_screenutil:
  dartz:
  flutter_bloc:
  bloc:
  salomon_bottom_bar:
  rxdart:
  top_snackbar_flutter: ^3.1.0
  visibility_detector: ^0.4.0+2
  image_picker: ^1.1.1
  mime: ^1.0.5
  http_parser: ^4.0.2
  # flutter_native_splash: ^2.4.0
  latlong2: ^0.9.0
  flutter_map:
  flutter_map_cancellable_tile_provider:
  socket_io_client:
  geolocator:
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^3.0.2
  auto_route_generator: ^8.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_gravity: fill

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svg/
    - .env

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf


